[package]
name = "mdns-sd-host-example"
version = "0.1.0"
edition = "2021"

[dependencies]
mdns-sd = "0.13.1"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
